import streamlit as st
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns


# Configure plot styles for better readability (will be applied once at app start)
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 8)
plt.rcParams["figure.dpi"] = 100

# All AI-BOM functions are now imported from utils.py


st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: AI-BOM Risk Navigator")
st.divider()
st.markdown("""
In this lab, the **AI-BOM Risk Navigator** is an interactive Streamlit application designed for Risk Managers to explore and assess risks within AI system supply chains. It provides a visual and data-driven approach to understanding component dependencies, identifying vulnerabilities, and simulating the cascading impact of compromised elements.

**Learning Goals:**
- Understand the concept and importance of an AI Bill of Materials (AI-BOM) for AI risk management.
- Learn how to generate and interpret a synthetic AI-BOM dataset.
- Visualize AI system dependencies and their structural integrity.
- Calculate and interpret individual component risk scores based on attributes like vulnerabilities and origin.
- Aggregate overall AI System Risk, accounting for component interdependencies.
- Simulate the propagation of a vulnerability throughout the AI system and visualize its impact.
- Assess specific risks related to data provenance and third-party components.
- Identify top and bottom risk components to prioritize mitigation efforts.
""")

# Initialize session state variables if they don't exist
if 'ai_bom_df' not in st.session_state:
    st.session_state.ai_bom_df = pd.DataFrame()
if 'ai_bom_dependencies' not in st.session_state:
    st.session_state.ai_bom_dependencies = []
if 'ai_system_graph' not in st.session_state:
    st.session_state.ai_system_graph = nx.DiGraph()
if 'simulated_risk_graph' not in st.session_state:
    st.session_state.simulated_risk_graph = nx.DiGraph()
if 'num_components_input' not in st.session_state:
    st.session_state.num_components_input = 15
if 'num_dependencies_input' not in st.session_state:
    st.session_state.num_dependencies_input = 20
if 'vulnerable_component_id_input' not in st.session_state:
    st.session_state.vulnerable_component_id_input = None
if 'base_impact_score_input' not in st.session_state:
    st.session_state.base_impact_score_input = 7.0
if 'num_top_bottom_n_input' not in st.session_state:
    st.session_state.num_top_bottom_n_input = 3


# Sidebar for navigation only
page = st.sidebar.selectbox(label="Navigation", options=[
    "Introduction", "AI-BOM Details", "Initial Dependencies",
    "Component Risk Profile", "Vulnerability Impact", "Targeted Risk Analysis"
], key='navigation_selectbox')

if page == "Introduction":
    from application_pages.page_1_introduction import main
    main()
elif page == "AI-BOM Details":
    from application_pages.page_2_ai_bom_details import main
    main()
elif page == "Initial Dependencies":
    from application_pages.page_3_initial_dependencies import main
    main()
elif page == "Component Risk Profile":
    from application_pages.page_4_component_risk_profile import main
    main()
elif page == "Vulnerability Impact":
    from application_pages.page_5_vulnerability_impact import main
    main()
elif page == "Targeted Risk Analysis":
    from application_pages.page_6_targeted_risk_analysis import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
